Db diagram
Ultro163/java-filmorate pull request #4
Opened 2024-07-25 16:44 UTC by Ultro163

Выполнил промежуточное задание.
Жду оценку проделанной работы.

2024-07-25 17:03 UTC, lazarx77 requested changes

2024-07-25 17:03 UTC, lazarx77 commented on README.md
> +![text](db_diagram.bmp)
Схема базы данных выполнена на мой взгляд правильно. Возможно я бы предложил в таблице friendship для поля status вместо enum использовать тип bit, который может принимать значения 0, 1 (или null, но полю можно выставить ограничение not null). Но это на усмотрение автора.
Также я бы добавил описание таблиц и их полей в readme, чтобы было легче разобраться в схеме.

2024-07-26 04:07 UTC, Ultro163 commented on README.md
> +![text](db_diagram.bmp)
Добавил примеры запросов.

2024-07-26 04:20 UTC, lazarx77 approved these changes

2024-07-26 04:34 UTC, merged